<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="GatewayWSServiceDefinitions" targetNamespace="http://com/cht/ws" xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://com/cht/ws" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/">
  <s0:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://com/cht/ws" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="describeServer">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="describeServerResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </s0:types>
  <s0:message name="describeServer">
    <s0:part element="s1:describeServer" name="parameters"/>
  </s0:message>
  <s0:message name="describeServerResponse">
    <s0:part element="s1:describeServerResponse" name="parameters"/>
  </s0:message>
  <s0:portType name="GatewayWS">
    <s0:operation name="describeServer" parameterOrder="parameters">
      <s0:input message="s1:describeServer"/>
      <s0:output message="s1:describeServerResponse"/>
    </s0:operation>
  </s0:portType>
  <s0:binding name="GatewayWSServiceSoapBinding" type="s1:GatewayWS">
    <s2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <s0:operation name="describeServer">
      <s2:operation soapAction="" style="document"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body parts="parameters" use="literal"/>
      </s0:output>
    </s0:operation>
  </s0:binding>
  <s0:service name="GatewayWSService">
    <s0:port binding="s1:GatewayWSServiceSoapBinding" name="GatewayWSSoapPort">
      <s2:address location="http://localhost:7001/Gateway_WS/GatewayWS"/>
    </s0:port>
  </s0:service>
</s0:definitions>