/**
 * DatabaseManagement_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.cht.ws.client.fc.database;

public interface DatabaseManagement_PortType extends java.rmi.Remote {
    public com.cht.ws.client.fc.database.DatabaseManagement_Type getInstance() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createTemplate(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getClientCount() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public byte[] getIcon(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName, java.lang.String itemId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeTemplate(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getDefaultTemplate(java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setDefaultTemplate(java.lang.String clientTypeName, java.lang.String deviceTypeName, java.lang.String templateid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeDefaultTemplate(java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listDefaultTemplates() throws java.rmi.RemoteException;
    public java.lang.String removeFeedApp(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeClient(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedDataSource(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeBrick(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeBatchHistory(java.lang.String batchId, java.lang.Boolean force) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removePackageIcon(java.lang.String packageId, java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public byte[] getPackageIcon(java.lang.String packageId, java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addPackageIcon(java.lang.String packageId, java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeDefaultPreference(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public byte[] getFca(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName, java.lang.String itemId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeCategory(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public void pollNowFS(java.lang.String batchId, java.lang.String datasourceId) throws java.rmi.RemoteException;
    public java.lang.String createAdmin(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public void logoutDeviceAll() throws java.rmi.RemoteException;
    public java.lang.String importZipFile(boolean overwrite) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listBricks() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeBrick(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listBrickProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getBrickProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setBrickProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeBrickProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createBrick(java.lang.String guid, java.lang.String name, java.lang.String desc, java.lang.String className, java.lang.String startup, java.lang.String feedsInput, java.lang.String feedsOutput, java.lang.String feedsExtract) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateBrick(java.lang.String guid, java.lang.String name, java.lang.String desc, java.lang.String className, java.lang.String startup, java.lang.String feedsInput, java.lang.String feedsOutput, java.lang.String feedsExtract) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateBrickAttribute(java.lang.String guid, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeeds() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeFeed(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeed(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getFeedProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setFeedProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createFeed(java.lang.String guid, java.lang.String name, java.lang.String desc, java.lang.String startup, java.lang.String type) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateFeed(java.lang.String guid, java.lang.String name, java.lang.String desc, java.lang.String startup, java.lang.String type) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateFeedAttribute(java.lang.String guid, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listInputBricksForFeed(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addInputBrickToFeed(java.lang.String guid, java.lang.String feedGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeInputBrickFromFeed(java.lang.String guid, java.lang.String feedGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listOutputBricksForFeed(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addOutputBrickToFeed(java.lang.String guid, java.lang.String feedGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeOutputBrickFromFeed(java.lang.String guid, java.lang.String feedGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listExtractBricksForFeed(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addExtractBrickToFeed(java.lang.String guid, java.lang.String feedGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeExtractBrickFromFeed(java.lang.String guid, java.lang.String feedGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedDataSourcesForFeed(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addFeedDataSourceToFeed(java.lang.String guid, java.lang.String dataSourceGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedDataSourceFromFeed(java.lang.String guid, java.lang.String dataSourceGuid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedDataSources() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeFeedDataSource(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedDataSourceProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getFeedDataSourceProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setFeedDataSourceProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedDataSourceProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createFeedDataSource(java.lang.String guid, java.lang.String name, java.lang.String className, int type, java.lang.String startup, int pollInterval, java.lang.String feedLog, java.lang.String feedGuid, java.lang.String contact, java.lang.String desc, java.lang.String url, java.lang.String username, java.lang.String password) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateFeedDataSource(java.lang.String guid, java.lang.String name, java.lang.String className, int type, java.lang.String startup, int pollInterval, java.lang.String feedLog, java.lang.String feedGuid, java.lang.String contact, java.lang.String desc, java.lang.String url, java.lang.String username, java.lang.String password) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String dssPublish(java.lang.String guid, boolean force) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String dssPublishAll(java.lang.String dssId, boolean force) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean pluginAdd(java.lang.String pluginfilename, java.lang.String dssURL, java.lang.String username, java.lang.String password, boolean force) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean pluginRemove(java.lang.String jarfilename, java.lang.String dssURL, java.lang.String username, java.lang.String password, boolean force) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String pluginList(java.lang.String dssURL, java.lang.String username, java.lang.String password) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateFeedDataSourceAttribute(java.lang.String guid, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String pollNow(java.lang.String datasourceId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public void pollNowDSS(java.lang.Object dssInfo, java.lang.String datasourceId, java.lang.String batchId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedApps(boolean commissionedOnly) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeFeedApp(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedAppProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listPackageProperties(java.lang.String id) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getFeedAppProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getPackageProperty(java.lang.String id, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setFeedAppProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setPackageProperty(java.lang.String id, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedAppProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removePackageProperty(java.lang.String id, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createFeedApp(java.lang.String guid, java.lang.String name, java.lang.String desc, java.lang.String version, java.lang.String startup, java.lang.String longDesc, java.lang.String subPeriod, float price, java.lang.String currency, int trialDays, java.lang.String trialPeriod, boolean isAutoRenew, long begin, long end, int channel, java.lang.String type, java.lang.String feedGuid, boolean decommissioned) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateFeedApp(java.lang.String guid, java.lang.String name, java.lang.String desc, java.lang.String version, java.lang.String startup, java.lang.String longDesc, java.lang.String subPeriod, float price, java.lang.String currency, int trialDays, java.lang.String trialPeriod, boolean isAutoRenew, long begin, long end, java.lang.String type, java.lang.String feedGuid, boolean decommissioned) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateFeedAppAttribute(java.lang.String guid, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listCategoriesForFeedApp(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addFeedAppToCategory(java.lang.String guid, java.lang.String catName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedAppFromCategory(java.lang.String guid, java.lang.String catName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getFeedAppThrottling(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setFeedAppThrottling(java.lang.String guid, java.lang.String profile) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedAppThrottling(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFcas(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addFca(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName, java.lang.String itemId, boolean preloadedOnClient) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFca(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName, java.lang.String itemId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAllFcas(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listDefaultPreferences(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getDefaultPreference(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setDefaultPreference(java.lang.String guid, java.lang.String clientTypeName, java.lang.String deviceTypeName, java.lang.String pref) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedAcl(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getFeedAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setFeedAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listDatasourceAcl(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getDatasourceAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setDatasourceAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeDatasourceAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedAppAcl(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getFeedAppAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setFeedAppAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeFeedAppAcl(java.lang.String guid, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getSubscriptionCountPerFeedApp() throws java.rmi.RemoteException;
    public java.lang.String listPackages(boolean commissionedOnly, java.lang.String type) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describePackage(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createPackage(java.lang.String id, java.lang.String name, java.lang.String desc, java.lang.String longDesc, int type, java.lang.String subPeriod, float price, java.lang.String currency, boolean isAutoRenew, long begin, long end, java.lang.Integer displayOrder, boolean decommissioned) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updatePackage(java.lang.String id, java.lang.String name, java.lang.String desc, java.lang.String longDesc, int type, java.lang.String subPeriod, float price, java.lang.String currency, boolean isAutoRenew, long begin, long end, java.lang.Integer displayOrder, boolean decommissioned) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updatePackageAttribute(java.lang.String id, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String removePackage(java.lang.String id) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.Object addFeedAppToPackage(java.lang.String packageId, java.lang.String feedAppId, boolean propagate, java.lang.Boolean fixed, java.lang.Boolean activate, java.lang.Boolean trial) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.Object removeFeedAppFromPackage(java.lang.String packageId, java.lang.String feedAppId, boolean propagate) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listPackageFeedApps(java.lang.String packageId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addPackageSubscription(java.lang.String deviceId, java.lang.String packageId, java.lang.Boolean activate) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updatePackageSubscription(java.lang.String deviceId, java.lang.String packageId, java.lang.Boolean activate, java.lang.Integer error) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listPackageSubscriptions(java.lang.String deviceId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean cancelPackageSubscription(java.lang.String deviceId, java.lang.String packageId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updatePackageSubscriptionAttribute(java.lang.String deviceId, java.lang.String packageId, java.lang.String attrName, java.lang.String attrValue) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listPackageAcl(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getPackageAcl(java.lang.String id, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setPackageAcl(java.lang.String id, java.lang.String requestorType, java.lang.String requestorName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removePackageAcl(java.lang.String id, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listTemplatePackageSubscriptions(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.Object addTemplatePackageSubscription(java.lang.String name, java.lang.String pkgId, java.lang.Boolean propagate, java.lang.Boolean activate) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.Object cancelTemplatePackageSubscription(java.lang.String name, java.lang.String pkgId, java.lang.Boolean propagate) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateTemplatePackageSubscriptionAttribute(java.lang.String name, java.lang.String pkgId, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listPackageIcons(java.lang.String packageId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getBatchHistory(java.lang.String batchId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listBatchHistory(java.lang.Integer from, java.lang.Integer to) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listCategories() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeCategory(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listCategoryProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getCategoryProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setCategoryProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeCategoryProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createCategory(java.lang.String name, java.lang.String desc, java.lang.String type, java.lang.Integer displayOrder, java.lang.String displayName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateCategory(java.lang.String name, java.lang.String desc, java.lang.String type, int displayOrder, java.lang.String displayName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateCategoryAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listFeedAppsForCategory(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listCategoryAcl(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getCategoryAcl(java.lang.String name, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setCategoryAcl(java.lang.String name, java.lang.String requestorType, java.lang.String requestorName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeCategoryAcl(java.lang.String name, java.lang.String requestorType, java.lang.String requestorName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getSubscriberCount() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listSubscriberProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getSubscriberProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeSubscriber(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setSubscriberProperty(java.lang.String name, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeSubscriberProperty(java.lang.String name, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createSubscriber(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeSubscriber(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateSubscriberAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listSubscriberClients(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addClientToSubscriber(java.lang.String clientName, java.lang.String subscriberName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeClientFromSubscriber(java.lang.String clientName, java.lang.String subscriberName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listSubscriberAcl(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getSubscriberAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setSubscriberAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeSubscriberAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listSubscriberMemberships(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addSubscriberToGroup(java.lang.String name, java.lang.String groupName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeSubscriberFromGroup(java.lang.String name, java.lang.String groupName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listSubscriberGroups() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeSubscriberGroup(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listSubscriberGroupProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getSubscriberGroupProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setSubscriberGroupProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeSubscriberGroupProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createSubscriberGroup(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateSubscriberGroup(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateSubscriberGroupAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeSubscriberGroup(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listSubscriberGroupAcl(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getSubscriberGroupAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setSubscriberGroupAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeSubscriberGroupAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getAdminCount() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAdmin(java.lang.String adminName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listAdminProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getAdminProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setAdminProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAdminProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeAdmin(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateAdminAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listAdminMemberships(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addAdminToGroup(java.lang.String name, java.lang.String groupName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAdminFromGroup(java.lang.String name, java.lang.String groupName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listAdminAcl(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getAdminAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setAdminAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAdminAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listAdminGroups() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeAdminGroup(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAdminGroup(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listAdminGroupProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getAdminGroupProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setAdminGroupProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAdminGroupProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createAdminGroup(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateAdminGroup(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateAdminGroupAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listAdminGroupAcl(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public int getAdminGroupAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setAdminGroupAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName, int permission) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeAdminGroupAcl(java.lang.String name, java.lang.String targetType, java.lang.String targetName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listTemplateIds() throws java.rmi.RemoteException;
    public java.lang.String describeTemplate(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listTemplateProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getTemplateProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setTemplateProperty(java.lang.String guid, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeTemplateProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeClient(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientProperties(java.lang.String guid) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getClientProperty(java.lang.String guid, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createClient(java.lang.String name, java.lang.String subscriberName, java.lang.String clientTypeName, java.lang.String deviceTypeName, java.lang.String templateId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.Object updateClient(java.lang.String name, java.lang.String subscriberName, java.lang.String clientTypeName, java.lang.String deviceTypeName) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String updateClientAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setClientProperty(java.lang.String name, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeClientProperty(java.lang.String name, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientSubscriptionStatistics(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientSynchronizationLevels(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getClientSynchronizationLevel(java.lang.String name, java.lang.String feedAppId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean resetClientSynchronizationLevel(java.lang.String name, java.lang.String feedAppId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientThrottleUsage(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getClientThrottleUsage(java.lang.String name, java.lang.String feedAppId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean resetClientThrottleUsage(java.lang.String name, java.lang.String feedAppId, java.lang.String pref) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listTemplateSubscriptions(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientSubscriptions(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.Object addTemplateSubscription(java.lang.String name, java.lang.String feedAppId, java.lang.Boolean propagate, java.lang.Boolean activate, java.lang.Boolean trial) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean addClientSubscription(java.lang.String name, java.lang.String feedAppId, java.lang.Boolean activate, java.lang.Boolean trial) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String addManyClientSubscription(java.lang.String feedAppId, java.lang.String clientType, java.lang.String deviceType, java.lang.Boolean activate, java.lang.Boolean trial) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean resetClientPreference(java.lang.String name, java.lang.String feedAppId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String resetManyClientPreference(java.lang.String feedappID, java.lang.String clientType, java.lang.String deviceType) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateTemplateSubscriptionAttribute(java.lang.String name, java.lang.String feedAppId, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateClientSubscriptionAttribute(java.lang.String name, java.lang.String feedAppId, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateClientSubscription(java.lang.String name, java.lang.String feedAppId, java.lang.Boolean activate, java.lang.Boolean trial, java.lang.Integer error) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.Object cancelTemplateSubscription(java.lang.String name, java.lang.String feedAppId, java.lang.Boolean propagate) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String cancelAllFeedAppSubscriptions(java.lang.String feedAppId, boolean includeTemplates) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String cancelManyClientSubscription(java.lang.String feedAppId, java.lang.String clientType, java.lang.String deviceType) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean cancelClientSubscription(java.lang.String name, java.lang.String feedAppId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listTemplatePreferences(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientPreferences(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setTemplatePreference(java.lang.String name, java.lang.String feedAppId, java.lang.String pref) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setClientPreference(java.lang.String name, java.lang.String feedAppId, java.lang.String pref) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeTemplatePreference(java.lang.String name, java.lang.String feedAppId, java.lang.String pref) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeClientPreference(java.lang.String name, java.lang.String feedAppId, java.lang.String pref) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getTemplatePreference(java.lang.String name, java.lang.String feedAppId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getClientPreference(java.lang.String name, java.lang.String feedAppId) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listDeviceTypes() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeDeviceType(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listDeviceTypeProperties(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getDeviceTypeProperty(java.lang.String name, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setDeviceTypeProperty(java.lang.String name, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeDeviceTypeProperty(java.lang.String name, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createDeviceType(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateDeviceType(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateDeviceTypeAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeDeviceType(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientTypes() throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String describeClientType(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String listClientTypeProperties(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String getClientTypeProperty(java.lang.String name, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean setClientTypeProperty(java.lang.String name, java.lang.String prop, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeClientTypeProperty(java.lang.String name, java.lang.String prop) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public java.lang.String createClientType(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateClientType(java.lang.String name, java.lang.String desc) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean updateClientTypeAttribute(java.lang.String name, java.lang.String attr, java.lang.String value) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
    public boolean removeClientType(java.lang.String name) throws java.rmi.RemoteException, com.cht.ws.client.fc.database.ManagementException;
}
